CREATE TABLE R(
	A int PRIMARY KEY,
	B int,
	C int UNIQUE
);

CREATE TABLE T(
D int PRIMARY KEY,
E int
);

CREATE TABLE S(
	C int,
	D int,
  CONSTRAINT FK_S_R FOREIGN KEY (C) REFERENCES R(C),
  CONSTRAINT FK_S_T FOREIGN KEY (D) REFERENCES T(D),
  primary key (C, D)
);
