CREATE TABLE R(
	A int PRIMARY KEY,
	B int,
	C int
);

CREATE TABLE T(
D int PRIMARY KEY,
E int
);

CREATE TABLE S(
	C int PRIMARY KEY,
	D int PRIMARY KEY,
  CONSTRAINT FK_S_R FOREIGN KEY (C) REFERENCES R(C),
  CONSTRAINT FK_S_T FOREIGN KEY (D) REFERENCES T(D)
);
